version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    expose:
      - "${METRICS_PORT}"
    ports:
      - "8081:8081"
    environment:
      KAFKA_BROKERS: "kafka:9092"  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    volumes:
      - ./logs/app.log:/app/logs/app.log
    networks:
      - kafka_net
      - observability_net
    

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    networks:
      - kafka_net
      - observability_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  observability_net:
    external: true
  kafka_net:
    external: true

