global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['prometheus:9090']
    # Принудительно задаем метки
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: "prometheus"


  - job_name: 'booking'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['booking:9191']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: "booking"


rule_files:
  - 'alerts.yml'


alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']



